select* from customer limit 20
-- 1 what is the total revenue generated by male vs female customer?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2 which customer used the discount but still spend more then the avg. purchse amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg (purchase_amount) from customer)

--3 which are the top 5 product eith the highest avg.review rating?

select item_purchased,avg(review_rating)as "average product rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5

--4 compare the avg. purchase amount b/w standard and express shipping?

select shipping_type,
ROUND (avg(purchase_amount),2) 
from customer
where  LOWER (shipping_type) in ('standard','free shipping')
group by shipping_type

--5 do subscribed customer spend more?
--compare avg. spend and total revenueb/w subscriber and non subscriber

select subscription_status,
count(customer_id) as total_customer,
ROUND(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc

--6 which 5 product has the highest % of purchase with discount applied

select item_purchased,
round (100* sum(CASE WHEN LOWER (discount_applied) = 'yes' then 1 else 0 end )	/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--7 suggest customer into new, returning,loyal based on their total number of previous purchase
-- show the count of each segment

with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases=1 then'NEW'
when previous_purchases BETWEEN 2 AND 10 then 'Returning'
else 'Loyal'
END AS customer_segment
from customer
)
select customer_segment ,count(*) as "number of customer"
from customer_type
group by customer_segment

--8 what are the top 3 most purchased product with in each category

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number () OVER (PARTITION BY category order by count(customer_id)desc)as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--9 are the customers who are the repeat buyers (more than 5 perivous purchase) also likely to subscribe
select subscription_status,
count(customer_id)as repeat_buyer
from customer
where previous_purchases>5
group by subscription_status

--10 what is the revenue contribution of each group
select age_group,
SUM (purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc

